---
- hosts: all
  become: yes
  roles:
    - {role: "oasishub.selenium-chrome"}
    - {role: "oasishub.selenium-grid"}
    - {role: "geerlingguy.supervisor",
      vars: {
        supervisor_programs:
        [{name: "selenium_server",
          command: "java -jar /home/{{ ansible_user }}/{{ selenium_server_jar }} -port 80 -role hub",
          state: present,
          configuration: {
            autostart=true
            autorestart=true
            startretries=1
            startsecs=1
            redirect_stderr=true
            stderr_logfile=/var/log/selenium-server-err.log
            stdout_logfile=/var/log/selenium-server-out.log
            user=root
            killasgroup=true
            stopasgroup=true
          }
        },
        {name: "selenium_webdriver",
         command: "java -Dwebdriver.chrome.driver=/home/{{ ansible_user }}/chromedriver -jar /home/{{ ansible_user }}/{{ selenium_server_jar }} -port 6666 -role node -hub http://localhost:80",
         state: present,
         configuration: {
            autostart=true
            autorestart=true
            startretries=1
            startsecs=1
            redirect_stderr=true
            stderr_logfile=/var/log/selenium-chromedriver-err.log
            stdout_logfile=/var/log/selenium-chromedriver-out.log
            user=root
            killasgroup=true
            stopasgroup=true
         }
        }]
      }

    }
