---
- name: add Google repository key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: add Google repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: install stable Chrome and dependencies
  apt:
    name:
    - google-chrome-stable
    - unzip
    state: latest

- name: install cron job to update Chrome
  cron:
    name: update chrome
    minute: 27
    hour: 2
    job: apt-get update && apt-get install google-chrome-stable

- name: create dir for driver
  file:
    path: "{{ chromedriver_dir }}"
    state: directory
    mode: "u=rwx,g=r,o=r"

- name: get Chrome driver
  get_url:
    url: "https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/{{ chromedriver_file }}"
    dest: "{{ chromedriver_dir }}"

- name: unarchive Chrome driver
  unarchive:
    remote_src: yes
    src: "{{ chromedriver_dir }}/{{ chromedriver_file }}"
    dest: "{{ chromedriver_dir }}"
